name: authentication_repository
description: Dart package which manages authentication.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  
dependencies: 
  cloud_firestore: ^3.1.17
  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.4.0
  firebase_storage: ^10.2.18
  flutter: 
    sdk: flutter
  google_sign_in: ^5.3.3

dev_dependencies:
  build_runner: ^2.1.11
  copy_with_extension_gen: ^4.0.0
  flutter_lints: ^1.0.0