name: music_service
description: Dart package which manages the audio api calls.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  
dependencies: 
  api_repository:
    path: ../api_repository
  audio_service: ^0.18.6 
  flutter: 
    sdk: flutter
  just_audio: ^0.9.27
  rxdart: ^0.27.4
