name: api_repository
description: Dart package which manages api requests.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies: 
  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  flutter: 
    sdk: flutter
  hive: ^2.2.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  just_audio: ^0.9.24
  just_audio_background: ^0.0.1-beta.5

dev_dependencies: 
  build_runner: ^2.1.11
  copy_with_extension_gen: ^4.0.0
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
