name: api_repository
description: Dart package which manages api requests.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies: 
  flutter: 
    sdk: flutter
    version: ^0.0.0
  hive: ^2.2.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  just_audio: ^0.9.24

dev_dependencies: 
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
