name: Deploy Web
on:
    push:
        branches:
            - main
jobs:
    deploy-web:
        runs-on: ubuntu-latest
        steps:
            - name: Performing Repository Checkout
              uses: actions/checkout@v2

            - name: Creating a Flutter environment
              uses: subosito/flutter-action@v1
              
            - name: Deploying with flutter-gh-pages
              uses: bluefireteam/flutter-gh-pages@v7
